services:
  # Base service with dependencies pre-installed
  game-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: orbital-game:latest
    volumes:
      - node_modules_cache:/app/node_modules
    command: ["echo", "Base image built"]

  # Development environment (hot reload at 9876)
  game-dev:
    image: orbital-game:latest
    depends_on:
      - game-base
    ports:
      - "9876:9876"
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Test environment (CI-equivalent)
  game-test:
    image: orbital-game:latest
    depends_on:
      - game-base
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    environment:
      - NODE_ENV=test
    command: npm test

  # Watch tests during development
  game-test-watch:
    image: orbital-game:latest
    depends_on:
      - game-base
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test:watch

  # Production static server for built assets in ./dist
  game-prod:
    image: nginx:alpine
    depends_on: []
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  node_modules_cache:
